######################################################################
# Automatically generated by qmake (2.01a) Mi. Nov 15 16:39:18 2017
######################################################################

TEMPLATE = app
TARGET = wayland_monte_carlo
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += /home/oliver/Programs/gems/gmml/includes/MolecularModeling/assembly.hpp \
           ../../gems/gmml/includes/GeometryTopology/coordinate.hpp \
           ../../gems/gmml/includes/GeometryTopology/plane.hpp \
           ../../gems/gmml/includes/common.hpp \
           ../../gems/gmml/includes/Glycan/sugarname.hpp \
           ../../gems/gmml/includes/Glycan/chemicalcode.hpp \
           ../../gems/gmml/includes/MolecularModeling/atom.hpp \
           ../../gems/gmml/includes/MolecularModeling/moleculardynamicatom.hpp \
           ../../gems/gmml/includes/MolecularModeling/quantommechanicatom.hpp \
           ../../gems/gmml/includes/MolecularModeling/dockingatom.hpp \
           ../../gems/gmml/includes/Glycan/monosaccharide.hpp \
           ../../gems/gmml/includes/Glycan/ontologyvocabulary.hpp \
           ../../gems/gmml/includes/InputSet/PdbFileSpace/pdbfile.hpp \
           ../../gems/gmml/includes/InputSet/PdbqtFileSpace/pdbqtfile.hpp \
           ../../gems/gmml/includes/InputSet/TopologyFileSpace/topologyfile.hpp \
           ../../gems/gmml/includes/InputSet/CoordinateFileSpace/coordinatefile.hpp \
           ../../gems/gmml/includes/ParameterSet/PrepFileSpace/prepfile.hpp \
           ../../gems/gmml/includes/ParameterSet/PrepFileSpace/prepfileresidue.hpp \
           ../../gems/gmml/includes/ParameterSet/PrepFileSpace/prepfileatom.hpp \
           ../../gems/gmml/includes/ParameterSet/LibraryFileSpace/libraryfile.hpp \
           ../../gems/gmml/includes/ParameterSet/ParameterFileSpace/parameterfile.hpp \
           ../../gems/gmml/includes/InputSet/PdbqtFileSpace/pdbqtmodelresidueset.hpp \
           ../../gems/gmml/includes/InputSet/PdbFileSpace/pdbmodelresidueset.hpp \
           ../../gems/gmml/includes/InputSet/PdbFileSpace/pdbmodelcard.hpp \
           ../../gems/gmml/includes/InputSet/PdbFileSpace/pdbmodel.hpp \
           ../../gems/gmml/includes/Glycan/oligosaccharide.hpp \
           ../../gems/gmml/includes/MolecularModeling/assembly.hpp \
           ../../gems/gmml/includes/Glycan/note.hpp \
           ../../gems/gmml/includes/InputSet/CondensedSequenceSpace/condensedsequence.hpp \
           ../../gems/gmml/includes/utils.hpp \
           ../../gems/gmml/includes/MolecularModeling/residue.hpp
SOURCES += main.cpp \
    main_wayland.cpp
